import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { buildBodAvenueReportModel } from "./bodAvenueReportModel.js";
import {
  BOD_AVENUE_REPORT_LAYOUT,
  BOD_AVENUE_REPORT_LETTERHEAD_URL,
  buildBodAvenueReportPdfDocument,
  buildBodAvenueReportPdfPages,
  getBodAvenueReportLetterheadPng,
  loadBodAvenueReportLetterheadPng,
  parseBodAvenueReportLetterheadPng,
} from "./bodAvenueReportPdf.js";
import { RESOLUTION_OFFICIAL_LETTERHEAD_URL } from "../resolutions/resolutionLetterhead.js";

const MOCK_LETTERHEAD = Object.freeze({
  bytes: new Uint8Array([0x78, 0x9c, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01]),
  width: 1414,
  height: 2000,
  bitsPerComponent: 8,
  colorSpace: "DeviceRGB",
  colors: 3,
});

const decodePdf = (bytes) => new TextDecoder("latin1").decode(bytes);
const occurrences = (value, pattern) => value.match(pattern)?.length || 0;

const makeEvent = (id, description = "Short description", startDate = "2026-07-05", avenues = ["CMD"], overrides = {}) => ({
  id,
  name: `Project ${id}`,
  startDate,
  recordKind: "clubEvent",
  isActive: true,
  archived: false,
  avenues,
  rcphRole: "host",
  hostClub: "Rotaract Club of Pune Heritage",
  collaborators: [{ name: "Partner Club" }],
  collaboratorsKnown: true,
  description,
  avenueDescriptions: {},
  ...overrides,
});

const makeMeeting = (id, description = "Meeting discussion", date = "2026-07-11", overrides = {}) => ({
  id,
  name: `BOD Meeting ${id}`,
  date,
  recordKind: "bodMeeting",
  type: "bodMeeting",
  isActive: true,
  archived: false,
  desc: description,
  ...overrides,
});

function report(events, options = {}) {
  return buildBodAvenueReportModel({
    month: options.month || "2026-07",
    avenueCode: options.avenueCode || "CMD",
    selectedMonths: options.selectedMonths,
    selectedAvenueCodes: options.selectedAvenueCodes,
    includeBodMeetings: options.includeBodMeetings,
    events,
    selectedEventIds: options.selectedEventIds || events.map((event) => event.id),
    directors: options.directors || [{ name: "Aarav Joshi", positionTitle: "Community Service Director" }],
    directorsByAvenue: options.directorsByAvenue,
    appearance: options.appearance,
    generatedAt: options.generatedAt || "2026-07-03T12:00:00.000Z",
  });
}

test("canonical BOD Avenue Report letterhead asset is the shared official Resolution A4 RGB PNG", () => {
  assert.equal(BOD_AVENUE_REPORT_LETTERHEAD_URL, RESOLUTION_OFFICIAL_LETTERHEAD_URL);
  const png = readFileSync(new URL("../../../public/images/RCPH_BOD_Avenue_Report_Letterhead_A4.png", import.meta.url));
  const parsed = parseBodAvenueReportLetterheadPng(png);
  assert.equal(parsed.width, 1414);
  assert.equal(parsed.height, 2000);
  assert.equal(parsed.bitsPerComponent, 8);
  assert.equal(parsed.colorSpace, "DeviceRGB");
  assert.ok(parsed.bytes.length > 400000);
});

test("BOD Avenue Report letterhead loads fresh so replaced public assets are not reused from browser cache", async () => {
  const requests = [];
  const fetchImpl = async (url, init) => {
    requests.push({ url, cache: init?.cache });
    return { ok: true, arrayBuffer: async () => new Uint8Array([requests.length]).buffer };
  };
  const parsePng = (value) => ({ ...MOCK_LETTERHEAD, bytes: new Uint8Array(value) });
  const first = await getBodAvenueReportLetterheadPng({ fetchImpl, parsePng });
  const second = await getBodAvenueReportLetterheadPng({ fetchImpl, parsePng });
  assert.deepEqual(requests, [
    { url: RESOLUTION_OFFICIAL_LETTERHEAD_URL, cache: "no-store" },
    { url: RESOLUTION_OFFICIAL_LETTERHEAD_URL, cache: "no-store" },
  ]);
  assert.deepEqual([...first.bytes], [1]);
  assert.deepEqual([...second.bytes], [2]);
});

test("finalized report produces an A4 portrait PDF with one shared full-page PNG background", () => {
  const pages = buildBodAvenueReportPdfPages(report([makeEvent("One")]));
  const pdf = decodePdf(buildBodAvenueReportPdfDocument(report([makeEvent("One")]), MOCK_LETTERHEAD));
  assert.match(pdf, /^%PDF-1\.4/);
  assert.match(pdf, /\/MediaBox \[0 0 595 842\]/);
  assert.equal(occurrences(pdf, /\/Subtype \/Image/g), 1);
  assert.equal(occurrences(pdf, /\/XObject << \/BG 7 0 R >>/g), pages.length);
  assert.equal(occurrences(pdf, /\/BG Do/g), pages.length);
  assert.match(pdf, /595\.00 0 0 841\.58 0\.00 0\.21 cm/);
});

test("single-selection default PDF renders the MOM-style title, summary, table, footer, and default appearance", () => {
  const model = report([makeEvent("One")]);
  const pdf = decodePdf(buildBodAvenueReportPdfDocument(model, MOCK_LETTERHEAD));
  for (const text of [
    "03/07/2026",
    "Page 1 of 1",
    "Generated by RCPH Website \\225 03/07/2026 at 5:30 PM IST",
    "Community Service Avenue Report",
    "Date",
    "Director name",
    "Total events",
    "July 2026",
    "Aarav Joshi",
    "Description",
    "Expense",
    "Project One",
    "Total expense for July 2026",
    "Rs. 0",
  ]) assert.match(pdf, new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.doesNotMatch(pdf, /\(Role\) Tj ET/);
  assert.doesNotMatch(pdf, /Host \/ Collaborators \/ Description/);
  assert.match(pdf, /\/F1 8 Tf/);
  assert.match(pdf, /\/F2 7\.7 Tf/);
});

test("long director names wrap inside the Director name summary cell without hiding report fields", () => {
  const pages = buildBodAvenueReportPdfPages(report([makeEvent("One")], {
    directors: [{ name: "A very long community service director name that must not collide with adjacent summary columns", positionTitle: "Community Service Director" }],
  }));
  const first = pages[0].join("\n");
  assert.match(first, /Director name/);
  assert.match(first, /A very long community service director name/);
  assert.match(first, /Date/);
  assert.match(first, /Total events/);
  assert.match(first, /Community Service Avenue Report/);
  assert.match(first, /Total expense for July 2026/);
});

test("grouped reports render avenue-month headings, director metadata, and repeated table headers", () => {
  const model = report([
    makeEvent("Multi", "Shared description", "2026-07-02", ["CMD", "PDD"], {
      avenueDescriptions: {
        CMD: "Community service group description",
        PDD: "Professional development group description",
      },
      reportFinance: {
        hasFinance: true,
        entries: [
          { type: "expense", amount: 10, description: "Venue" },
          { type: "income", amount: 999, description: "Tickets" },
        ],
      },
    }),
    makeEvent("August", "August description", "2026-08-03", ["CMD"], {
      reportFinance: { hasFinance: true, entries: [{ type: "expense", amount: 25.5, description: "Materials" }] },
    }),
  ], {
    selectedMonths: ["2026-07", "2026-08"],
    selectedAvenueCodes: ["CMD", "PDD"],
    directorsByAvenue: {
      CMD: [{ name: "Aarav Joshi", positionTitle: "Community Service Director" }],
      PDD: [{ name: "Mira Shah", positionTitle: "Professional Development Director" }],
    },
  });
  const pdf = decodePdf(buildBodAvenueReportPdfDocument(model, MOCK_LETTERHEAD));
  for (const text of [
    "BOD Avenue Report",
    "Date",
    "Director name",
    "Total events",
    "Community Service Avenue",
    "Professional Development Avenue",
    "July 2026",
    "August 2026",
    "Director name: Aarav Joshi",
    "Director name: Mira Shah",
    "Total expense for July 2026",
    "Total expense for August 2026",
    "Grand total expense",
    "Rs. 10",
    "Rs. 25.50",
    "Rs. 35.50",
  ]) assert.match(pdf, new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.equal(occurrences(pdf, /Project Multi/g), 2);
  assert.match(pdf, /Community service group description/);
  assert.match(pdf, /Professional development group description/);
  assert.ok(occurrences(pdf, /\(Description\) Tj ET/g) >= model.groupCount);
  assert.ok(occurrences(pdf, /\(Expense\) Tj ET/g) >= model.groupCount);
  assert.doesNotMatch(pdf, /\(Role\) Tj ET/);
  assert.doesNotMatch(pdf, /Host \/ Collaborators \/ Description/);
});

test("PDF expense cells use expense totals only and ignore income entries", () => {
  const model = report([
    makeEvent("Finance", "Finance summary", "2026-07-09", ["CMD"], {
      reportFinance: {
        hasFinance: true,
        entries: [
          { type: "income", amount: 5000, description: "Member collections" },
          { type: "expense", amount: 1250.46, description: "Venue booking" },
          { type: "expense", amount: 249.54, description: "Refreshments" },
        ],
      },
    }),
  ]);
  const pdf = decodePdf(buildBodAvenueReportPdfDocument(model, MOCK_LETTERHEAD));
  assert.match(pdf, /Project Finance/);
  assert.match(pdf, /Rs\. 1,500/);
  assert.match(pdf, /Total expense for July 2026/);
  assert.doesNotMatch(pdf, /Rs\. 5,000/);
  assert.doesNotMatch(pdf, /Rs\. 6,500/);
});

test("meeting-only PDFs render a BOD Meetings section without requiring an avenue", () => {
  const model = report([
    makeMeeting("Finance", "Treasurer brief and monthly minutes", "2026-07-11", {
      reportFinance: { hasFinance: true, entries: [{ type: "expense", amount: 75, description: "Printouts" }] },
    }),
  ], { selectedAvenueCodes: [], includeBodMeetings: true });
  const pdf = decodePdf(buildBodAvenueReportPdfDocument(model, MOCK_LETTERHEAD));
  for (const text of [
    "BOD Meetings Report",
    "BOD Meetings - July 2026",
    "Director name",
    "Not available",
    "Date",
    "Event",
    "Description",
    "Expense",
    "BOD Meeting Finance",
    "Treasurer brief and monthly minutes",
    "Rs. 75",
    "Total expense for July 2026",
  ]) assert.match(pdf, new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.doesNotMatch(pdf, /Community Service Avenue Report/);
});

test("mixed club event and BOD meeting PDFs keep meetings after normal avenue sections", () => {
  const model = report([
    makeEvent("Club", "Club event summary", "2026-07-05", ["CMD"]),
    makeMeeting("Review", "Board reviewed service pipeline", "2026-07-06"),
  ], { selectedAvenueCodes: ["CMD"], includeBodMeetings: true });
  const pageText = buildBodAvenueReportPdfPages(model)[0].join("\n");
  assert.match(pageText, /BOD Monthly Report/);
  assert.match(pageText, /Community Service Avenue/);
  assert.match(pageText, /BOD Meetings - July 2026/);
  assert.ok(pageText.indexOf("Community Service Avenue") < pageText.indexOf("BOD Meetings - July 2026"));
  assert.match(pageText, /Project Club/);
  assert.match(pageText, /BOD Meeting Review/);
});

test("director names are emitted as separate PDF text lines when directorLines are available", () => {
  const model = report([makeEvent("Directors")], {
    directors: [
      { name: "Aarav Joshi", positionTitle: "Community Service Director" },
      { name: "Mira Shah", positionTitle: "Joint Community Service Director" },
    ],
  });
  const commands = buildBodAvenueReportPdfPages(model)[0];
  const aaravCommand = commands.find((command) => command.includes("Aarav Joshi"));
  const miraCommand = commands.find((command) => command.includes("Mira Shah"));
  assert.ok(aaravCommand);
  assert.ok(miraCommand);
  assert.notEqual(aaravCommand, miraCommand);
});

test("same-page report groups render month totals before the next avenue section", () => {
  const pages = buildBodAvenueReportPdfPages(report([
    makeEvent("One", "Short", "2026-07-01", ["CMD"]),
    makeEvent("Two", "Short", "2026-07-02", ["PDD"]),
  ], {
    selectedMonths: ["2026-07"],
    selectedAvenueCodes: ["CMD", "PDD"],
    directorsByAvenue: { CMD: [], PDD: [] },
  }));
  const pageText = pages[0].join("\n");
  assert.ok(pageText.indexOf("Total expense for July 2026") < pageText.indexOf("Professional Development Avenue"));
  assert.ok(pageText.includes("Director name: Not available"));
  assert.match(pageText, /Description/);
  assert.match(pageText, /Expense/);
});

test("group heading pagination keeps heading, director metadata, table header, and first row together", () => {
  const model = report([
    makeEvent("One", "Long detail ".repeat(170), "2026-07-01", ["CMD"]),
    makeEvent("Two", "Short detail", "2026-07-02", ["PDD"]),
  ], {
    selectedMonths: ["2026-07"],
    selectedAvenueCodes: ["CMD", "PDD"],
    directorsByAvenue: { CMD: [], PDD: [] },
  });
  const pages = buildBodAvenueReportPdfPages(model);
  const pddPage = pages.find((page) => page.join("\n").includes("Professional Development Avenue"));
  assert.ok(pddPage);
  const text = pddPage.join("\n");
  assert.match(text, /Director name: Not available/);
  assert.match(text, /Description/);
  assert.match(text, /Expense/);
  assert.match(text, /Project Two/);
});

test("no grouped report page leaves an orphaned group heading without its first row", () => {
  const model = report([
    makeEvent("One", "Long detail ".repeat(80), "2026-07-01", ["CMD"]),
    makeEvent("Two", "Short detail", "2026-07-02", ["PDD"]),
    makeEvent("Three", "Short detail", "2026-07-03", ["ISD"]),
  ], {
    selectedMonths: ["2026-07"],
    selectedAvenueCodes: ["ISD", "CMD", "PDD"],
    directorsByAvenue: { ISD: [], CMD: [], PDD: [] },
  });
  const expected = [
    ["International Service Avenue", "Project Three"],
    ["Community Service Avenue", "Project One"],
    ["Professional Development Avenue", "Project Two"],
  ];
  const pages = buildBodAvenueReportPdfPages(model);
  for (const [heading, firstEvent] of expected) {
    const page = pages.find((item) => item.join("\n").includes(heading));
    assert.ok(page, heading);
    const text = page.join("\n");
    assert.match(text, /Director name: Not available/);
    assert.match(text, /Description/);
    assert.match(text, /Expense/);
    assert.match(text, new RegExp(firstEvent));
  }
});

test("multi-page reports repeat table headers and resolve Page X of Y after pagination", () => {
  const events = Array.from({ length: 15 }, (_, index) => makeEvent(`Event-${index + 1}`, "Long project detail ".repeat(35), `2026-07-${String(index + 1).padStart(2, "0")}`));
  const pages = buildBodAvenueReportPdfPages(report(events));
  assert.ok(pages.length > 1);
  pages
    .filter((page) => page.some((command) => command.includes("Project Event-")))
    .forEach((page) => {
      assert.ok(page.some((command) => command.includes("Description")));
      assert.ok(page.some((command) => command.includes("Expense")));
    });
  const pdf = decodePdf(buildBodAvenueReportPdfDocument(report(events), MOCK_LETTERHEAD));
  for (let page = 1; page <= pages.length; page += 1) assert.match(pdf, new RegExp(`Page ${page} of ${pages.length}`));
});

test("event rows are measured and moved wholly to the next page when they do not fit", () => {
  const events = [
    makeEvent("Tall", "Tall project detail ".repeat(100), "2026-07-01"),
    makeEvent("Moved", "Moved project detail ".repeat(20), "2026-07-02"),
  ];
  const pages = buildBodAvenueReportPdfPages(report(events));
  assert.ok(pages.length > 1);
  assert.equal(pages[0].join("\n").includes("Project Moved"), false);
  const pagesWithMoved = pages.filter((page) => page.join("\n").includes("Project Moved"));
  assert.equal(pagesWithMoved.length, 1);
});

test("normal event rows are not split across pages", () => {
  const events = Array.from({ length: 9 }, (_, index) => makeEvent(`Keep-${index + 1}`, "Keep together detail ".repeat(42), `2026-07-${String(index + 1).padStart(2, "0")}`));
  const pages = buildBodAvenueReportPdfPages(report(events));
  for (const event of events) {
    const pagesWithEvent = pages.filter((page) => page.join("\n").includes(`Project ${event.id}`));
    assert.equal(pagesWithEvent.length, 1, `${event.id} should appear on exactly one page`);
  }
});

test("exceptionally tall rows use a bounded continuation fallback instead of looping forever", () => {
  const pages = buildBodAvenueReportPdfPages(report([makeEvent("Huge", "Huge project detail ".repeat(1200))]));
  assert.ok(pages.length > 1);
  assert.equal(pages.filter((page) => page.join("\n").includes("Project Huge")).length, 1);
  assert.equal(pages.slice(1).some((page) => page.join("\n").includes("\\(continued\\)")), true);
});

test("report body content stays inside the declared top and bottom safe boundaries", () => {
  const pages = buildBodAvenueReportPdfPages(report(Array.from({ length: 6 }, (_, index) => makeEvent(`Safe-${index + 1}`, "Safe content detail ".repeat(35)))));
  const { safeArea, topMeta, generatedMeta } = BOD_AVENUE_REPORT_LAYOUT;
  assert.equal(topMeta.y, 735);
  assert.equal(safeArea.top, 670);
  assert.equal(BOD_AVENUE_REPORT_LAYOUT.title.top, 670);
  assert.equal(topMeta.gray, 0.2);
  assert.equal(generatedMeta.y, 85);
  assert.equal(generatedMeta.fontSize, 8.2);
  assert.equal(generatedMeta.gray, 0.3);
  assert.equal(BOD_AVENUE_REPORT_LAYOUT.table.fontSize, 8);
  assert.equal(BOD_AVENUE_REPORT_LAYOUT.table.lineHeight, 10.1);
  for (const command of pages.flat()) {
    if (command.includes(`${topMeta.y.toFixed(1)} Td`) || command.includes(`${generatedMeta.y.toFixed(1)} Td`)) continue;
    for (const match of command.matchAll(/\b(\d+\.\d) (\d+\.\d) Td/g)) {
      const y = Number(match[2]);
      assert.ok(y >= safeArea.bottom, command);
      assert.ok(y <= safeArea.top, command);
    }
  }
});

test("appearance controls affect font resources, row measurement, and pagination", () => {
  const events = Array.from({ length: 8 }, (_, index) => makeEvent(`Style-${index + 1}`, "Style detail ".repeat(45), `2026-07-${String(index + 1).padStart(2, "0")}`));
  const defaultPages = buildBodAvenueReportPdfPages(report(events));
  const large = report(events, { appearance: { fontFamily: "times", bodySize: "large", density: "comfortable" } });
  const largePages = buildBodAvenueReportPdfPages(large);
  const pdf = decodePdf(buildBodAvenueReportPdfDocument(large, MOCK_LETTERHEAD));
  assert.ok(largePages.length > defaultPages.length);
  assert.match(pdf, /\/BaseFont \/Times-Roman/);
  assert.match(pdf, /\/F3 10 Tf/);
});

test("compact Helvetica reports use compact metrics without losing table content", () => {
  const model = report([makeEvent("Compact")], { appearance: { fontFamily: "helvetica", bodySize: "compact", density: "compact" } });
  const pdf = decodePdf(buildBodAvenueReportPdfDocument(model, MOCK_LETTERHEAD));
  assert.match(pdf, /\/F1 7\.5 Tf/);
  assert.match(pdf, /Project Compact/);
});

test("unselected events never enter the PDF and supported punctuation is normalized safely", () => {
  const pdf = decodePdf(buildBodAvenueReportPdfDocument(report([
    makeEvent("Selected", "Pune's community - Jose"),
    makeEvent("Excluded"),
  ], { selectedEventIds: ["Selected"] }), MOCK_LETTERHEAD));
  assert.match(pdf, /Project Selected/);
  assert.doesNotMatch(pdf, /Project Excluded/);
  assert.match(pdf, /Pune's community - Jose/);
});

test("empty, inconsistent, or unbranded report models cannot create PDFs", () => {
  assert.throws(() => buildBodAvenueReportPdfDocument({ eventCount: 0, events: [] }, MOCK_LETTERHEAD), /non-empty/i);
  assert.throws(() => buildBodAvenueReportPdfDocument(report([makeEvent("One")]), null), /letterhead PNG/i);
});

test("letterhead asset failures are logged without report data and return safe user copy", async () => {
  const logs = [];
  await assert.rejects(loadBodAvenueReportLetterheadPng({
    fetchImpl: async () => ({ ok: false, status: 404 }),
    logger: { error: (...args) => logs.push(args) },
  }), /letterhead could not be loaded/i);
  assert.equal(logs.length, 1);
  assert.equal(JSON.stringify(logs).includes("Project"), false);
  assert.equal(JSON.stringify(logs).includes(BOD_AVENUE_REPORT_LETTERHEAD_URL), true);
});
