import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { buildBodAvenueReportModel } from "./bodAvenueReportModel.js";
import {
  BOD_AVENUE_REPORT_LAYOUT,
  BOD_AVENUE_REPORT_LETTERHEAD_URL,
  buildBodAvenueReportPdfDocument,
  buildBodAvenueReportPdfPages,
  loadBodAvenueReportLetterheadPng,
  parseBodAvenueReportLetterheadPng,
} from "./bodAvenueReportPdf.js";

const MOCK_LETTERHEAD = Object.freeze({
  bytes: new Uint8Array([0x78, 0x9c, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01]),
  width: 1414,
  height: 2000,
  bitsPerComponent: 8,
  colorSpace: "DeviceRGB",
  colors: 3,
});

const decodePdf = (bytes) => new TextDecoder("latin1").decode(bytes);
const occurrences = (value, pattern) => value.match(pattern)?.length || 0;

const makeEvent = (id, description = "Short description", startDate = "2026-07-05") => ({
  id,
  name: `Project ${id}`,
  startDate,
  recordKind: "clubEvent",
  isActive: true,
  archived: false,
  avenues: ["CMD"],
  rcphRole: "host",
  hostClub: "Rotaract Club of Pune Heritage",
  collaborators: [{ name: "Partner Club" }],
  collaboratorsKnown: true,
  description,
});

function report(events, options = {}) {
  return buildBodAvenueReportModel({
    month: "2026-07",
    avenueCode: "CMD",
    events,
    selectedEventIds: options.selectedEventIds || events.map((event) => event.id),
    directors: options.directors || [{ name: "Aarav Joshi", positionTitle: "Community Service Director" }],
    generatedAt: options.generatedAt || "2026-07-03T12:00:00.000Z",
  });
}

test("canonical BOD Avenue Report letterhead asset is an A4 RGB PNG", () => {
  assert.equal(BOD_AVENUE_REPORT_LETTERHEAD_URL, "/images/RCPH_BOD_Avenue_Report_Letterhead_A4.png");
  const png = readFileSync(new URL("../../../public/images/RCPH_BOD_Avenue_Report_Letterhead_A4.png", import.meta.url));
  const parsed = parseBodAvenueReportLetterheadPng(png);
  assert.equal(parsed.width, 1414);
  assert.equal(parsed.height, 2000);
  assert.equal(parsed.bitsPerComponent, 8);
  assert.equal(parsed.colorSpace, "DeviceRGB");
  assert.ok(parsed.bytes.length > 400000);
});

test("finalized report produces an A4 portrait PDF with one shared full-page PNG background", () => {
  const pages = buildBodAvenueReportPdfPages(report([makeEvent("One")]));
  const pdf = decodePdf(buildBodAvenueReportPdfDocument(report([makeEvent("One")]), MOCK_LETTERHEAD));
  assert.match(pdf, /^%PDF-1\.4/);
  assert.match(pdf, /\/MediaBox \[0 0 595 842\]/);
  assert.equal(occurrences(pdf, /\/Subtype \/Image/g), 1);
  assert.equal(occurrences(pdf, /\/XObject << \/BG 5 0 R >>/g), pages.length);
  assert.equal(occurrences(pdf, /\/BG Do/g), pages.length);
  assert.match(pdf, /595\.00 0 0 841\.58 0\.00 0\.21 cm/);
});

test("date, dynamic page numbering, IST metadata, summary, and table render on the report", () => {
  const model = report([makeEvent("One")]);
  const pdf = decodePdf(buildBodAvenueReportPdfDocument(model, MOCK_LETTERHEAD));
  for (const text of [
    "03/07/2026",
    "Page 1 of 1",
    "Generated by RCPH Website • 03/07/2026 at 5:30 PM IST",
    "Month",
    "Director Name",
    "Avenue",
    "Total Events",
    "July 2026",
    "Aarav Joshi",
    "Community Service Avenue",
    "Host / Collaborators / Description",
    "Project One",
  ]) assert.match(pdf, new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
});

test("long director names wrap the summary into a second row without hiding report fields", () => {
  const pages = buildBodAvenueReportPdfPages(report([makeEvent("One")], {
    directors: [{ name: "A very long community service director name that must not collide with adjacent summary columns", positionTitle: "Community Service Director" }],
  }));
  const first = pages[0].join("\n");
  assert.match(first, /Director Name/);
  assert.match(first, /A very long community service director name/);
  assert.match(first, /Month/);
  assert.match(first, /Avenue/);
  assert.match(first, /Total Events/);
  const directorLabelY = Number(first.match(/Director Name\) Tj ET[\s\S]*?BT [\d.]+ g \/F1 8\.1 Tf 36\.0 ([\d.]+) Td/)?.[1]);
  assert.ok(directorLabelY < BOD_AVENUE_REPORT_LAYOUT.summary.top - 20);
});

test("multi-page reports repeat table headers and resolve Page X of Y after pagination", () => {
  const events = Array.from({ length: 15 }, (_, index) => makeEvent(`Event-${index + 1}`, "Long project detail ".repeat(35), `2026-07-${String(index + 1).padStart(2, "0")}`));
  const pages = buildBodAvenueReportPdfPages(report(events));
  assert.ok(pages.length > 1);
  pages.forEach((page) => assert.ok(page.some((command) => command.includes("Host / Collaborators / Description"))));
  const pdf = decodePdf(buildBodAvenueReportPdfDocument(report(events), MOCK_LETTERHEAD));
  for (let page = 1; page <= pages.length; page += 1) assert.match(pdf, new RegExp(`Page ${page} of ${pages.length}`));
});

test("event rows are measured and moved wholly to the next page when they do not fit", () => {
  const events = [
    makeEvent("Tall", "Tall project detail ".repeat(80), "2026-07-01"),
    makeEvent("Moved", "Moved project detail ".repeat(20), "2026-07-02"),
  ];
  const pages = buildBodAvenueReportPdfPages(report(events));
  assert.ok(pages.length > 1);
  assert.equal(pages[0].join("\n").includes("Project Moved"), false);
  assert.equal(pages[1].join("\n").includes("Project Moved"), true);
});

test("normal event rows are not split across pages", () => {
  const events = Array.from({ length: 9 }, (_, index) => makeEvent(`Keep-${index + 1}`, "Keep together detail ".repeat(42), `2026-07-${String(index + 1).padStart(2, "0")}`));
  const pages = buildBodAvenueReportPdfPages(report(events));
  for (const event of events) {
    const pagesWithEvent = pages.filter((page) => page.join("\n").includes(`Project ${event.id}`));
    assert.equal(pagesWithEvent.length, 1, `${event.id} should appear on exactly one page`);
  }
});

test("exceptionally tall rows use a bounded continuation fallback instead of looping forever", () => {
  const pages = buildBodAvenueReportPdfPages(report([makeEvent("Huge", "Huge project detail ".repeat(1200))]));
  assert.ok(pages.length > 1);
  assert.equal(pages.filter((page) => page.join("\n").includes("Project Huge")).length, 1);
  assert.equal(pages.slice(1).some((page) => page.join("\n").includes("\\(continued\\)")), true);
});

test("report body content stays inside the declared top and bottom safe boundaries", () => {
  const pages = buildBodAvenueReportPdfPages(report(Array.from({ length: 6 }, (_, index) => makeEvent(`Safe-${index + 1}`, "Safe content detail ".repeat(35)))));
  const { safeArea, topMeta, generatedMeta } = BOD_AVENUE_REPORT_LAYOUT;
  assert.equal(topMeta.y, 704);
assert.equal(topMeta.gray, 0.2);

assert.equal(generatedMeta.y, 90);
assert.equal(generatedMeta.fontSize, 8.2);
assert.equal(generatedMeta.gray, 0.3);

assert.equal(BOD_AVENUE_REPORT_LAYOUT.table.fontSize, 8);
assert.equal(BOD_AVENUE_REPORT_LAYOUT.table.lineHeight, 10.1);
  for (const command of pages.flat()) {
    if (command.includes(`${topMeta.y.toFixed(1)} Td`) || command.includes(`${generatedMeta.y.toFixed(1)} Td`)) continue;
    for (const match of command.matchAll(/\b(\d+\.\d) (\d+\.\d) Td/g)) {
      const y = Number(match[2]);
      assert.ok(y >= safeArea.bottom, command);
      assert.ok(y <= safeArea.top, command);
    }
  }
});

test("unselected events never enter the PDF and supported punctuation is normalized safely", () => {
  const pdf = decodePdf(buildBodAvenueReportPdfDocument(report([
    makeEvent("Selected", "Pune's community - Jose"),
    makeEvent("Excluded"),
  ], { selectedEventIds: ["Selected"] }), MOCK_LETTERHEAD));
  assert.match(pdf, /Project Selected/);
  assert.doesNotMatch(pdf, /Project Excluded/);
  assert.match(pdf, /Pune's community - Jose/);
});

test("empty, inconsistent, or unbranded report models cannot create PDFs", () => {
  assert.throws(() => buildBodAvenueReportPdfDocument({ eventCount: 0, events: [] }, MOCK_LETTERHEAD), /non-empty/i);
  assert.throws(() => buildBodAvenueReportPdfDocument(report([makeEvent("One")]), null), /letterhead PNG/i);
});

test("letterhead asset failures are logged without report data and return safe user copy", async () => {
  const logs = [];
  await assert.rejects(loadBodAvenueReportLetterheadPng({
    fetchImpl: async () => ({ ok: false, status: 404 }),
    logger: { error: (...args) => logs.push(args) },
  }), /letterhead could not be loaded/i);
  assert.equal(logs.length, 1);
  assert.equal(JSON.stringify(logs).includes("Project"), false);
  assert.equal(JSON.stringify(logs).includes(BOD_AVENUE_REPORT_LETTERHEAD_URL), true);
});
