/* eslint no-unused-vars: ["error", { "argsIgnorePattern": "^file$" }] */
import { useState } from "react";
import AdminModuleHeader from "../AdminModuleHeader";
import AdminDialog from "../shared/AdminDialog";
import { AdminEmpty } from "../shared/AdminStates";
import { AVENUES, buildFinePayload, formatInr, safeUrl } from "../shared/adminModel";
import { addFine, deleteFine, deleteTreasury, newTreasuryId, setTreasuryById, updateTreasury, uploadTreasuryBill } from "../shared/adminService";
import useAdminMutation from "../shared/useAdminMutation";

export function FinesModule({ fines, members, lock, uid, onNotice }) {
  const empty = { memberId: "", reason: "", eventName: "", date: "", amount: "" }; const [draft, setDraft] = useState(empty); const [target, setTarget] = useState(null); const { busy, run } = useAdminMutation({ uid, module: "fines", onNotice }); const locked = lock.status !== "success" || lock.locked; const total = fines.reduce((sum, fine) => sum + fine.amount, 0);
  function submit(e) { e.preventDefault(); const member = members.find((item) => item.id === draft.memberId); const payload = buildFinePayload({ ...draft, memberName: member?.name || "" }); if (!payload.memberId || !payload.reason || !payload.eventName || !payload.date || payload.amount === null) return; run("add-fine", () => addFine(payload), "Fine added.").then((r) => { if (r) setDraft(empty); }); }
  return <><AdminModuleHeader title="Sergeant-at-Arms: Fines" description="Production supports add and permanent delete; no paid, waived, or archive states exist." /><div className={`admin-lock-banner ${locked ? "is-locked" : ""}`}>{locked ? "Fines are locked or lock status is unavailable." : `${fines.length} records · ${formatInr(total)}`}</div><section className="admin-panel"><form className="admin-form admin-form--inline" onSubmit={submit}><label>Member<select value={draft.memberId} onChange={(e) => setDraft({ ...draft, memberId: e.target.value })} required><option value="">Choose member</option>{members.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Reason<select value={draft.reason} onChange={(e) => setDraft({ ...draft, reason: e.target.value })} required><option value="">Choose reason</option><option value="missing_badge">Missing badge</option><option value="late">Late to event/meeting</option></select></label><label>Event/meeting<input value={draft.eventName} onChange={(e) => setDraft({ ...draft, eventName: e.target.value })} required /></label><label>Date<input type="date" value={draft.date} onChange={(e) => setDraft({ ...draft, date: e.target.value })} required /></label><label>Amount INR<input type="number" min="0" step="1" value={draft.amount} onChange={(e) => setDraft({ ...draft, amount: e.target.value })} required /></label><button disabled={locked || busy}>Add fine</button></form></section>{fines.length ? <div className="admin-table-wrap"><table><caption>Fine records</caption><thead><tr><th>Member</th><th>Amount</th><th>Reason</th><th>Event</th><th>Date</th><th>Action</th></tr></thead><tbody>{fines.map((fine) => <tr key={fine.id}><td>{fine.memberName || fine.memberId}</td><td>{formatInr(fine.amount)}</td><td>{fine.reason}</td><td>{fine.eventName}</td><td>{fine.date}</td><td><button className="danger" disabled={locked} onClick={() => setTarget(fine)}>Delete</button></td></tr>)}</tbody></table></div> : <AdminEmpty message="No fine records." />}{target ? <AdminDialog title="Permanently delete fine?" busy={busy} onClose={() => setTarget(null)}><p>This matches production behavior and cannot be undone.</p><div className="admin-actions"><button onClick={() => setTarget(null)}>Cancel</button><button className="danger" onClick={() => run("delete-fine", () => deleteFine(target.id), "Fine permanently deleted.").then((r) => { if (r !== null) setTarget(null); })}>Delete permanently</button></div></AdminDialog> : null}</>;
}

export function TreasuryModule({ transactions, members, lock, uid, onNotice }) {
  const empty = { title: "", type: "income", amount: "", date: "", avenue: "", purpose: "", paidBy: "", paidByType: "other", paidByMemberId: "", paidTo: "", paidToType: "other", paidToMemberId: "", paymentMode: "", referenceNumber: "", reimbursementStatus: "Not Applicable", reimbursedTo: "", reimbursementDate: "", billUrl: "" };
  const [draft, setDraft] = useState(empty); const [file, setFile] = useState(null); const [editing, setEditing] = useState(null); const [target, setTarget] = useState(null); const { busy, run } = useAdminMutation({ uid, module: "treasury", onNotice }); const locked = lock.status !== "success" || lock.locked;
  const income = transactions.filter((x) => x.type === "income").reduce((s, x) => s + x.amount, 0); const expense = transactions.filter((x) => x.type === "expense").reduce((s, x) => s + x.amount, 0);
  function payload(source) { return { ...source, title: source.title.trim(), name: source.title.trim(), amount: Number(source.amount), linkedEventName: source.purpose.trim(), cheque: source.referenceNumber.trim(), reimburse: source.reimbursementStatus, billUrl: safeUrl(source.billUrl) }; }
  async function submit(e) { e.preventDefault(); const value = payload(draft); if (!value.title || !value.date || !value.avenue || !(value.amount > 0)) return; await run("create-transaction", async () => { const id = newTreasuryId(); if (file) { if (file.size > 10 * 1024 * 1024 || !["application/pdf", "image/jpeg", "image/png", "image/webp"].includes(file.type)) throw new Error("Invalid treasury bill file."); Object.assign(value, await uploadTreasuryBill(file, value, id)); } await setTreasuryById(id, value); return { ok: true }; }, "Treasury transaction saved.").then((r) => { if (r) { setDraft(empty); setFile(null); } }); }
  async function saveEdit(e) { e.preventDefault(); const value = payload(editing); const result = await run("update-transaction", () => updateTreasury(editing.id, value), "Treasury transaction updated."); if (result !== null) setEditing(null); }
  return <><AdminModuleHeader title="Treasury" description="Income, expenses, reimbursements, bill links, and production Drive upload tickets." /><div className={`admin-lock-banner ${locked ? "is-locked" : ""}`}>{locked ? "Treasury is locked or unavailable." : `Income ${formatInr(income)} · Expense ${formatInr(expense)} · Net ${formatInr(income - expense)}`}</div><section className="admin-panel"><h3>Add transaction</h3><TreasuryForm value={draft} setValue={setDraft} members={members} onSubmit={submit} busy={busy || locked} file={file} setFile={setFile} /></section>{transactions.length ? <div className="admin-table-wrap"><table><caption>Treasury transactions</caption><thead><tr><th>Title</th><th>Type</th><th>Amount</th><th>Date</th><th>Avenue</th><th>Paid by/to</th><th>Reimbursement</th><th>Bill</th><th>Actions</th></tr></thead><tbody>{transactions.map((item) => <tr key={item.id}><td>{item.title}</td><td>{item.type}</td><td>{formatInr(item.amount)}</td><td>{item.date}</td><td>{item.avenue}</td><td>{item.paidBy || "-"} / {item.paidTo || "-"}</td><td>{item.reimbursementStatus}</td><td>{item.billUrl ? <a href={item.billUrl} target="_blank" rel="noopener noreferrer">Open</a> : "None"}</td><td><button disabled={locked} onClick={() => setEditing({ ...item })}>Edit</button><button className="danger" disabled={locked} onClick={() => setTarget(item)}>Delete</button></td></tr>)}</tbody></table></div> : <AdminEmpty message="No treasury transactions." />}{editing ? <AdminDialog title={`Edit ${editing.title}`} busy={busy} onClose={() => setEditing(null)} className="admin-dialog--wide"><TreasuryForm value={editing} setValue={setEditing} members={members} onSubmit={saveEdit} busy={busy} /></AdminDialog> : null}{target ? <AdminDialog title="Permanently delete transaction?" busy={busy} onClose={() => setTarget(null)}><p>This matches production behavior and does not delete an externally uploaded Drive bill.</p><div className="admin-actions"><button onClick={() => setTarget(null)}>Cancel</button><button className="danger" onClick={() => run("delete-transaction", () => deleteTreasury(target.id), "Treasury transaction permanently deleted.").then((r) => { if (r !== null) setTarget(null); })}>Delete permanently</button></div></AdminDialog> : null}</>;
}

function TreasuryForm({ value, setValue, members, onSubmit, busy, file, setFile }) { const set = (key) => (e) => setValue({ ...value, [key]: e.target.value }); return <form className="admin-form" onSubmit={onSubmit}><div className="admin-form-grid"><label>Title<input value={value.title} onChange={set("title")} required /></label><label>Type<select value={value.type} onChange={set("type")}><option value="income">Income</option><option value="expense">Expense</option></select></label><label>Amount INR<input type="number" min="0.01" step="0.01" value={value.amount} onChange={set("amount")} required /></label><label>Date<input type="date" value={value.date} onChange={set("date")} required /></label><label>Avenue<select value={value.avenue} onChange={set("avenue")} required><option value="">Choose</option>{[...AVENUES, "Other"].map((x) => <option key={x}>{x}</option>)}</select></label><label>Purpose<input value={value.purpose} onChange={set("purpose")} /></label><label>Paid by<select value={value.paidBy} onChange={set("paidBy")}><option value="">Other/none</option><option value="Rotaract Club of Pune Heritage">Club</option>{members.map((m) => <option key={m.id} value={m.name}>{m.name}</option>)}</select></label><label>Paid to<input value={value.paidTo} onChange={set("paidTo")} /></label><label>Payment mode<select value={value.paymentMode} onChange={set("paymentMode")}><option value="">Choose</option>{["Cash", "UPI", "Bank Transfer", "Cheque", "Card", "Other"].map((x) => <option key={x}>{x}</option>)}</select></label><label>Reference<input value={value.referenceNumber} onChange={set("referenceNumber")} /></label><label>Reimbursement<select value={value.reimbursementStatus} onChange={set("reimbursementStatus")}><option>Not Applicable</option><option>Pending</option><option>Done</option></select></label><label>Reimbursed to<input value={value.reimbursedTo} onChange={set("reimbursedTo")} /></label><label>Reimbursement date<input type="date" value={value.reimbursementDate} onChange={set("reimbursementDate")} /></label><label>Existing bill URL<input type="url" value={value.billUrl} onChange={set("billUrl")} /></label>{setFile ? <label>Upload bill<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label> : null}</div><button disabled={busy}>Save transaction</button></form>; }
