function freezeList(items) {
  return Object.freeze(items.filter(Boolean));
}

function makePreview(label, rows, type = "summary") {
  return Object.freeze({
    type,
    label,
    rows: freezeList(rows),
  });
}

function entry({ id, title, purpose, whoUses, canDo, steps, notes, preview }) {
  return Object.freeze({
    id,
    title,
    purpose,
    whoUses: freezeList(whoUses),
    canDo: freezeList(canDo),
    steps: freezeList(steps),
    notes: freezeList(notes),
    preview,
  });
}

function sharedDashboard(roleName, detail) {
  return entry({
    id: "dashboard",
    title: "Dashboard",
    purpose: `Your ${roleName} dashboard is the starting point after login. It summarizes the website areas and club information most relevant to your role.`,
    whoUses: [roleName],
    canDo: ["Review your account view", "Open announcements and club updates", "Move to your approved tools", detail],
    steps: ["Sign in with your approved account.", "Open Dashboard from the Access Hub.", "Scan the top summary and action links.", "Use the available sections to open the information you need."],
    notes: ["Dashboard content is based on your approved role and verified access.", "This guide preview is static and does not display real account data."],
    preview: makePreview("Dashboard snapshot", ["Role summary", "Announcements", "Upcoming activity"]),
  });
}

function editProfile(roleName) {
  return entry({
    id: "edit-profile",
    title: "Edit Profile",
    purpose: "The profile editor lets you keep your basic member details accurate for club records and website display where applicable.",
    whoUses: [roleName],
    canDo: ["Review your saved profile fields", "Update editable personal details", "Save changes from the profile dialog"],
    steps: ["Open your dashboard.", "Choose Edit profile from the dashboard actions.", "Update the available fields.", "Review validation messages, then save."],
    notes: ["Only fields exposed in the profile editor can be changed here.", "Role and permission changes are handled through trusted admin workflows, not this guide."],
    preview: makePreview("Profile dialog", ["Name and email", "Phone and RID", "Optional details"]),
  });
}

function announcements(roleName) {
  return entry({
    id: "announcements",
    title: "Announcements",
    purpose: "Announcements show role-targeted club messages, reminders, and updates that are relevant to your account.",
    whoUses: [roleName],
    canDo: ["Read current notices", "Open safe attachments when available", "Mark notices as read or remove them from your own dashboard"],
    steps: ["Open your dashboard.", "Find the Announcements section near the top.", "Read the newest items first.", "Use the available card actions only when needed."],
    notes: ["Announcements are informational and may differ by role.", "Removing a notice from your dashboard does not delete the club announcement."],
preview: makePreview("Announcement card", ["Priority label", "Message body", "Read state"], "announcementCard"),  });
}

function publicCalendar(roleName) {
  return entry({
    id: "public-event-calendar",
    title: "Public Event Calendar",
    purpose: "The public calendar gives a date-based view of published club events and district opportunities.",
    whoUses: [roleName, "Visitors"],
    canDo: ["Browse upcoming public activities", "Switch between calendar and list views", "Open event details for date, avenue, and description"],
    steps: ["Open Public Event Calendar from Access Hub or navigation.", "Use the calendar controls to move between months.", "Select an event to read its details.", "Use the list view on smaller screens when scanning many events."],
    notes: ["The public calendar is informational and does not mark attendance.", "Private admin scheduling tools are separate from the public calendar."],
    preview: makePreview("Calendar card", ["Month view", "Event list", "Avenue colors"]),
  });
}

function resolutions(roleName) {
  return entry({
    id: "resolutions",
    title: "Resolutions",
    purpose: "Resolutions help eligible members review governance items and complete the voting or confirmation flow assigned to them.",
    whoUses: [roleName, "Eligible voters"],
    canDo: ["Review open resolutions", "Read the resolution body and meeting context", "Submit the available vote or follow email confirmation steps"],
    steps: ["Open your dashboard or the approved Resolutions area.", "Read the resolution title, body, and voting method.", "Choose the available response when voting is open.", "Follow any email confirmation instructions shown by the page."],
    notes: ["Resolution permissions are controlled by trusted access rules.", "Closed, ineligible, or final items may not show voting controls."],
    preview: makePreview("Resolution card", ["Meeting label", "Resolution body", "Vote choices"]),
  });
}

const PRESIDENT_ADMIN_FEATURES = freezeList([
  entry({
    id: "access-hub",
    title: "Access Hub",
    purpose: "Access Hub is the approved-account landing area that lists the destinations available to your role.",
    whoUses: ["President", "Admin", "Approved account holders"],
    canDo: ["Review role and position summary", "Open dashboards and admin areas", "Return to public website areas"],
    steps: ["Sign in with an approved account.", "Open Access Hub after login.", "Choose the destination that matches your task.", "Return to Access Hub when switching between tools."],
    notes: ["Access Hub only displays areas already granted to the account.", "This guide is added as a static help destination."],
    preview: makePreview("Destination list", ["Dashboard", "Admin Tools", "Website Guide"]),
  }),
  entry({
    id: "admin-tools",
    title: "Admin Tools",
    purpose: "Admin Tools centralize operational modules for member records, events, attendance, finance, reports, and governance support.",
    whoUses: ["President", "Admin", "Approved delegated officers"],
    canDo: ["Navigate module workspaces", "Review operational summaries", "Open records that your access allows"],
    steps: ["Open Admin Tools from Access Hub.", "Use the sidebar or mobile module selector.", "Choose the module for the current task.", "Read notices and validation messages before taking actions."],
    notes: ["This guide does not add or change any admin authority.", "Real admin changes still require the existing module permissions."],
    preview: makePreview("Admin shell", ["Module sidebar", "Command center", "Status notice"]),
  }),
  entry({
    id: "members",
    title: "Members",
    purpose: "The Members workspace helps administrators review member roster information and account-linked profile context.",
    whoUses: ["President", "Admin"],
    canDo: ["Search and scan members", "Open member details", "Use existing profile or roster actions when permitted"],
    steps: ["Open Admin Tools.", "Choose Members.", "Search or filter the roster.", "Select a member row to review details.", "Use only the action needed for the approved task."],
    notes: ["Member records are protected operational data.", "The mini preview here is static and contains no real roster information."],
    preview: makePreview("Roster preview", ["Search members", "Member row", "Profile summary"]),
  }),
  entry({
    id: "attendance",
    title: "Attendance",
    purpose: "Attendance tools help authorized officers record and review club attendance for eligible events.",
    whoUses: ["President", "Admin", "Sergeant-at-Arms when delegated"],
    canDo: ["Select an event", "Review eligible member rows", "Mark or audit attendance where allowed"],
    steps: ["Open Admin Tools.", "Choose Club Attendance.", "Select the relevant event or meeting.", "Review the attendance grid.", "Save changes only after checking the selected rows."],
    notes: ["Attendance edits are real operational actions in the live module.", "This guide only explains the workflow and does not mark attendance."],
    preview: makePreview("Attendance grid", ["Event selector", "Member rows", "Present or absent marks"]),
  }),
  entry({
    id: "bod-operations",
    title: "BOD Operations",
    purpose: "BOD Operations supports board meeting and BOD attendance workflows inside the admin area.",
    whoUses: ["President", "Admin", "BOD officers with approved access"],
    canDo: ["Review BOD meetings", "Manage BOD attendance where authorized", "Connect meeting records to reporting needs"],
    steps: ["Open Admin Tools.", "Choose BOD Operations.", "Select the meeting or attendance view.", "Review the records before taking an action.", "Use notices to confirm whether a change succeeded."],
    notes: ["BOD operations access is permission controlled.", "Meeting reporting and MOM workflows may appear in related modules."],
    preview: makePreview("BOD operations", ["Meeting list", "Attendance status", "Reporting context"]),
  }),
  entry({
    id: "district",
    title: "District",
    purpose: "District tools track district-level events and participation information that is separate from club-only activity.",
    whoUses: ["President", "Admin"],
    canDo: ["Review district events", "Scan district attendance records", "Support district reporting"],
    steps: ["Open Admin Tools.", "Choose District.", "Review available district activities.", "Check attendance or reporting context.", "Use module actions according to the live permissions."],
    notes: ["District records should be kept separate from club event records.", "This guide does not submit district reports."],
    preview: makePreview("District workspace", ["District events", "Attendance summary", "Report notes"]),
  }),
  entry({
    id: "announcements",
    title: "Announcements",
    purpose: "Admins use Announcements to publish important updates to dashboards and optionally email the same message to selected recipients.",
    whoUses: ["President", "Admin"],
    canDo: [
      "Publish dashboard announcements.",
      "Select recipient groups.",
      "Choose specific recipients.",
      "Add optional image/PDF attachment.",
      "Add an optional action button/link.",
      "Set an expiry date/time.",
      "Optionally send the announcement by email too.",
    ],
    steps: [
      "Enter a clear title.",
      "Write the message.",
      "Select priority.",
      "Add attachment or action link if needed.",
      "Choose recipient groups or specific recipients.",
      "Tick email option only when the announcement should also be emailed.",
      "Publish.",
    ],
    notes: [
      "Use email only for important announcements.",
      "Attachments should be image/PDF and within size limits.",
      "Recipient groups and specific recipients can be combined.",
      "Expired announcements should no longer appear after their expiry.",
    ],
    preview: makePreview("Announcements form", ["Title", "Recipients", "Publish announcement"], "announcementForm"),
  }),
  resolutions("President or Admin"),
  entry({
    id: "reminders",
    title: "Reminders",
    purpose: "Reminders help authorized officers prepare operational follow-ups for events, meetings, and reporting windows.",
    whoUses: ["President", "Admin", "Approved delegated officers"],
    canDo: ["Review reminder queues", "Open event or meeting reminder context", "Track relevant follow-up windows"],
    steps: ["Open Admin Tools.", "Choose Reminders.", "Select the reminder category.", "Review the people, dates, and status shown by the module.", "Use the live controls only when a real reminder needs action."],
    notes: ["Reminder access can vary by officer assignment.", "This guide never sends reminder messages."],
    preview: makePreview("Reminder panel", ["Reminder type", "Due window", "Status"]),
  }),
  entry({
    id: "fines",
    title: "Fines",
    purpose: "The Fines module supports finance-linked tracking for fines connected to attendance or club operations.",
    whoUses: ["President", "Admin", "Treasury officers where approved"],
    canDo: ["Review fine records", "Filter by event or member context", "Support reconciliation with treasury records"],
    steps: ["Open Admin Tools.", "Choose Fines.", "Review filters and summary totals.", "Open the relevant record details.", "Use live module actions only after confirming the context."],
    notes: ["Fines may affect member-facing records and should be handled carefully.", "This guide contains no financial data."],
    preview: makePreview("Fines ledger", ["Member", "Reason", "Amount"]),
  }),
  entry({
    id: "treasury",
    title: "Treasury",
    purpose: "Treasury tools help approved officers review and manage finance records and supporting attachments.",
    whoUses: ["President", "Admin", "Treasury officers where approved"],
    canDo: ["Review treasury entries", "Check amounts and categories", "Open supporting file areas when available"],
    steps: ["Open Admin Tools.", "Choose Treasury.", "Review summaries before opening details.", "Check dates, amounts, and notes.", "Use the live module controls according to treasury policy."],
    notes: ["Treasury data is sensitive operational information.", "The guide preview is generic and static."],
    preview: makePreview("Treasury record", ["Date", "Category", "Amount"]),
  }),
  entry({
    id: "locks",
    title: "Locks",
    purpose: "Locks control whether certain operational windows are open or closed for protected workflows.",
    whoUses: ["President", "Admin with lock authority"],
    canDo: ["Review lock states", "Understand which modules are currently restricted", "Use existing lock controls if authorized"],
    steps: ["Open Admin Tools.", "Choose Locks.", "Review each lock description and state.", "Confirm the operational impact before changing anything in the live module.", "Return to the affected module to verify the expected state."],
    notes: ["Lock permissions are intentionally narrow.", "This guide does not alter lock states."],
    preview: makePreview("Lock states", ["Attendance lock", "BOD lock", "Treasury lock"]),
  }),
  entry({
    id: "reports",
    title: "Reports",
    purpose: "Reports provide read-focused summaries or exports that support admin review and club reporting.",
    whoUses: ["President", "Admin"],
    canDo: ["Review report-ready event data", "Check summary information", "Use existing export or report controls where available"],
    steps: ["Open Admin Tools.", "Choose Reports.", "Select the reporting context.", "Review the generated summary.", "Use live export controls only when the report is ready."],
    notes: ["Reports reflect the records available to the current account.", "This guide does not generate downloadable files."],
    preview: makePreview("Report summary", ["Period", "Events", "Totals"]),
  }),
  entry({
    id: "club-visits",
    title: "Club Visits",
    purpose: "Club Visits supports supporting-file uploads and review for visits such as Club Assembly, DZR Visit, and DRR Visit.",
    whoUses: ["President", "Admin", "BOD officers with approved visit access"],
    canDo: ["Review visit submission folders", "Upload approved supporting files in the live module", "Track submission status"],
    steps: ["Open Club Visits from Access Hub or Admin Tools.", "Choose the visit type or folder shown to you.", "Review existing submission guidance.", "Use the live upload controls only for real supporting documents.", "Check the upload status before leaving the page."],
    notes: ["Visit file handling uses the existing protected module.", "This guide does not upload files."],
    preview: makePreview("Visit submission", ["Visit type", "File queue", "Status"]),
  }),
]);

export const GUIDE_ROLES = freezeList([
  { id: "prospect", label: "Prospect" },
  { id: "gbm", label: "GBM" },
  { id: "bod", label: "BOD" },
  { id: "president", label: "President" },
  { id: "secretary", label: "Secretary" },
  { id: "sergeant-at-arms", label: "Sergeant-at-Arms" },
  { id: "admin", label: "Admin" },
  { id: "cwd", label: "CWD / Website Director" },
]);

export const WEBSITE_GUIDE_CONTENT = Object.freeze({
  prospect: freezeList([
    sharedDashboard("Prospect", "Track your prospect progress and next membership steps"),
    editProfile("Prospect"),
    entry({
      id: "prospect-progress",
      title: "Prospect Progress",
      purpose: "Prospect Progress explains where you are in the verified path toward club membership.",
      whoUses: ["Prospects"],
      canDo: ["View attendance progress", "Check dues or review status", "Understand the next step in the membership journey"],
      steps: ["Open your dashboard.", "Find the Prospect Progress section.", "Review each milestone in order.", "Use the next-action card to understand what comes next."],
      notes: ["Progress is based on verified club records.", "The guide preview does not calculate eligibility."],
      preview: makePreview("Progress path", ["Attendance milestone", "Dues status", "Membership review"]),
    }),
    announcements("Prospect"),
    publicCalendar("Prospect"),
  ]),
  gbm: freezeList([
    sharedDashboard("GBM", "Review your attendance, resolutions, and upcoming events"),
    editProfile("GBM"),
    entry({
      id: "attendance",
      title: "Attendance",
      purpose: "Attendance on the member dashboard shows your verified club participation and recent activity.",
      whoUses: ["GBMs", "BODs", "Admins"],
      canDo: ["Review your attendance percentage", "Scan recent marked events", "Compare club and district attendance summaries when available"],
      steps: ["Open your dashboard.", "Find the attendance feature area.", "Review the percentage and recent event list.", "Use the calendar link to plan future attendance."],
      notes: ["Attendance shown here is read-only for members.", "Corrections should be handled through the approved club process."],
      preview: makePreview("Attendance summary", ["Percentage", "Recent events", "Avenue breakdown"]),
    }),
    announcements("GBM"),
    resolutions("GBM"),
    publicCalendar("GBM"),
  ]),
  bod: freezeList([
    sharedDashboard("BOD", "Move between your dashboard, BOD tools, and approved reporting areas"),
    editProfile("BOD"),
    entry({
      id: "bod-tools",
      title: "BOD Tools",
      purpose: "BOD Tools support approved board workflows such as club event management and avenue reporting.",
      whoUses: ["BODs", "President", "Admin"],
      canDo: ["Create and review club events in the live module", "Open BOD event details", "Prepare avenue report material where available"],
      steps: ["Open BOD Tools from Access Hub or your dashboard.", "Review the event list and filters.", "Open an event or the report panel needed for your task.", "Use live actions only after confirming the event and avenue context."],
      notes: ["BOD Tools remain permission controlled.", "This guide does not create, edit, sync, or archive events."],
      preview: makePreview("BOD tools", ["Event list", "Avenue report", "MOM area"]),
    }),
    entry({
      id: "club-events",
      title: "Club Events",
      purpose: "Club Events are the approved activity records that power public event views, attendance context, and reporting.",
      whoUses: ["BODs", "President", "Admin"],
      canDo: ["Review event details", "Understand public and avenue descriptions", "Track reporting context for completed events"],
      steps: ["Open BOD Tools.", "Use filters to find the event.", "Open the event details.", "Review dates, avenues, descriptions, and related files.", "Return to the list before switching tasks."],
      notes: ["Public-facing event details may differ from internal report descriptions.", "This guide only shows a static event card."],
      preview: makePreview("Event card", ["Event name", "Avenue tags", "Report status"]),
    }),
    entry({
      id: "mom-upload-view",
      title: "MOM Upload/View",
      purpose: "MOM Upload/View helps eligible officers attach or review Minutes of Meeting files connected to BOD and club meeting records.",
      whoUses: ["Secretary", "President", "Admin", "BOD viewers with access"],
      canDo: ["View available MOM files", "Upload a PDF in the live module if authorized", "Open meeting-linked MOM context"],
      steps: ["Open the relevant BOD Tools or admin meeting area.", "Find the MOM section for the meeting.", "Review any existing file details.", "Use upload controls only when you are the responsible officer.", "Confirm the uploaded or viewed state."],
      notes: ["MOM upload permissions are not changed by this guide.", "Only the live module can upload or open protected files."],
      preview: makePreview("MOM panel", ["Meeting", "PDF status", "View or upload state"]),
    }),
    resolutions("BOD"),
    entry({
      id: "club-visits",
      title: "Club Visits",
      purpose: "Club Visits helps approved BOD officers submit supporting files for official club visit requirements.",
      whoUses: ["BODs with approved visit access", "President", "Admin"],
      canDo: ["Open assigned visit folders", "Review upload guidance", "Track submitted file status"],
      steps: ["Open Club Visits from Access Hub when available.", "Choose the visit type shown to your account.", "Review the allowed file types and folder guidance.", "Upload files only in the live module when ready.", "Check the status after each upload."],
      notes: ["Visit access depends on trusted role and position rules.", "This guide does not upload or list real files."],
      preview: makePreview("Visit card", ["Visit type", "Folder", "Files"]),
    }),
    publicCalendar("BOD"),
  ]),
  president: PRESIDENT_ADMIN_FEATURES,
  secretary: freezeList([
    entry({
      id: "mom-upload-view",
      title: "MOM Upload/View",
      purpose: "MOM Upload/View is the Secretary-facing path for handling meeting minutes files in the approved live modules.",
      whoUses: ["Secretary", "President", "Admin"],
      canDo: ["Review meeting-linked MOM state", "Upload approved PDF minutes when allowed", "Open available MOM files"],
      steps: ["Open the relevant BOD or admin meeting area.", "Find the MOM section for the meeting.", "Check whether a file already exists.", "Upload the final PDF in the live module if you are authorized.", "Verify the resulting status before leaving."],
      notes: ["Only approved PDF files should be uploaded.", "This guide does not access Drive or upload storage."],
      preview: makePreview("Secretary MOM", ["Meeting record", "PDF file", "Upload status"]),
    }),
    entry({
      id: "mom-email",
      title: "MOM Email",
      purpose: "MOM Email helps the Secretary prepare meeting minutes communication with the right subject, recipients, and attachment context.",
      whoUses: ["Secretary", "President", "Admin"],
      canDo: ["Review prepared email context", "Check recipient and subject guidance", "Confirm attachment readiness"],
      steps: ["Open the MOM area for the relevant meeting.", "Review the email panel if available.", "Check the subject, recipient guidance, and attachment state.", "Send or record email status only through the live approved workflow."],
      notes: ["Email sending behavior remains controlled by the existing module.", "The static preview does not send messages."],
      preview: makePreview("MOM email", ["Recipients", "Subject", "Attachment"]),
    }),
    resolutions("Secretary"),
    entry({
      id: "gbm-bod-meeting-reporting",
      title: "GBM/BOD Meeting reporting",
      purpose: "Meeting reporting helps the Secretary organize meeting records, attendance context, MOM files, and governance follow-up.",
      whoUses: ["Secretary", "President", "Admin"],
      canDo: ["Track meeting records", "Connect MOM and attendance context", "Support resolution or reminder follow-up"],
      steps: ["Open the approved meeting or admin area.", "Select the GBM or BOD meeting context.", "Review attendance, MOM, and resolution needs.", "Complete live module actions only after the meeting details are final."],
      notes: ["Reporting responsibilities can vary by club process.", "This guide is a checklist-style overview only."],
      preview: makePreview("Meeting report", ["Meeting type", "Attendance", "MOM status"]),
    }),
    entry({
      id: "secretary-reminders",
      title: "Reminders relevant to Secretary",
      purpose: "Secretary reminders highlight follow-ups tied to minutes, meeting reporting, and governance tasks.",
      whoUses: ["Secretary", "President", "Admin"],
      canDo: ["Review Secretary-specific reminder context", "Track meeting follow-up windows", "Coordinate with admin or president review"],
      steps: ["Open Reminders if the module is available to your account.", "Filter or review Secretary-relevant items.", "Check due dates and meeting references.", "Use live actions only when a reminder needs real follow-up."],
      notes: ["Reminder visibility depends on approved access.", "This guide does not create or send reminders."],
      preview: makePreview("Secretary reminders", ["MOM due", "Meeting report", "Status"]),
    }),
  ]),
  "sergeant-at-arms": freezeList([
    entry({
      id: "attendance-marking",
      title: "Attendance Marking",
      purpose: "Attendance Marking is the Sergeant-at-Arms workflow for recording presence in approved attendance modules.",
      whoUses: ["Sergeant-at-Arms", "President", "Admin"],
      canDo: ["Select the relevant event or meeting", "Mark attendance rows in the live module", "Review saved status"],
      steps: ["Open the attendance module available to your account.", "Choose the event or meeting.", "Review the member list carefully.", "Mark attendance in the live module.", "Save only after confirming the selected rows."],
      notes: ["Attendance marking changes real records in the live module.", "This guide is read-only and cannot mark attendance."],
      preview: makePreview("Marking grid", ["Event", "Member row", "Attendance mark"]),
    }),
    entry({
      id: "attendance-reminder",
      title: "Attendance Reminder",
      purpose: "Attendance Reminder helps the Sergeant-at-Arms understand reminder windows tied to attendance completion.",
      whoUses: ["Sergeant-at-Arms", "President", "Admin"],
      canDo: ["Review attendance follow-up context", "Check reminders for unmarked events", "Coordinate completion with admin teams"],
      steps: ["Open Reminders if available.", "Review attendance-related items.", "Check the event or meeting reference.", "Take any real follow-up only through the live module or club process."],
      notes: ["Reminder access may be delegated and role-specific.", "This guide does not send reminders."],
      preview: makePreview("Attendance reminder", ["Event due", "Pending marks", "Follow-up"]),
    }),
    entry({
      id: "bod-club-attendance",
      title: "BOD/Club Attendance",
      purpose: "BOD/Club Attendance separates board attendance and club event attendance so each record type can be handled in the right place.",
      whoUses: ["Sergeant-at-Arms", "President", "Admin"],
      canDo: ["Understand which attendance area to use", "Review BOD meeting attendance", "Review club event attendance"],
      steps: ["Choose Club Attendance for regular club events.", "Choose BOD Operations for board meeting attendance.", "Confirm the event or meeting date before editing.", "Review saved states after any live update."],
      notes: ["Using the wrong attendance area can create reporting confusion.", "This guide only explains the difference."],
      preview: makePreview("Attendance types", ["Club event", "BOD meeting", "Saved status"]),
    }),
  ]),
  admin: PRESIDENT_ADMIN_FEATURES,
  cwd: freezeList([
    sharedDashboard("CWD / Website Director", "Use the dashboard as your personal view before switching to support tasks"),
    editProfile("CWD / Website Director"),
    entry({
      id: "website-guide",
      title: "Website Guide",
      purpose: "Website Guide is the static help center you are reading now. It explains website areas by role without touching live data.",
      whoUses: ["All approved users", "CWD / Website Director"],
      canDo: ["Switch roles in the guide", "Choose a feature to read instructions", "Use static previews to understand page layout"],
      steps: ["Open Website Guide from Access Hub or dashboard links.", "Choose the role that matches your task.", "Choose a feature from the second dropdown.", "Read the purpose, steps, notes, and preview."],
      notes: ["The guide does not call Firestore or Firebase Functions.", "Mini previews are static markup only."],
      preview: makePreview("Guide selector", ["Role dropdown", "Feature dropdown", "Guide content"]),
    }),
    entry({
      id: "admin-tools-if-authority",
      title: "Admin Tools if admin authority exists",
      purpose: "Website Directors may see Admin Tools only when server-verified authority grants that access.",
      whoUses: ["CWD / Website Director with approved authority", "President"],
      canDo: ["Open Admin Tools only when the link is visible", "Support website-related operational tasks", "Return to Access Hub to verify available destinations"],
      steps: ["Open Access Hub.", "Check whether Admin Tools appears in your destinations.", "If present, open Admin Tools and use only the module needed.", "If absent, continue with dashboard and website support areas."],
      notes: ["Position names do not grant admin access by themselves.", "This guide does not change permissions."],
      preview: makePreview("Authority check", ["Access Hub", "Admin Tools link", "Role summary"]),
    }),
    entry({
      id: "reminders-cwd-reporting-window",
      title: "Reminders / CWD reporting window",
      purpose: "CWD reminder context helps the Website Director track website-support or reporting windows when those reminders are available.",
      whoUses: ["CWD / Website Director", "President", "Admin"],
      canDo: ["Review visible reminder context", "Track website-support follow-up", "Coordinate reporting timing with club leadership"],
      steps: ["Open Reminders only if it is visible to your account.", "Review CWD or website-related items.", "Check dates, references, and status.", "Use live reminder actions only when you are responsible for that follow-up."],
      notes: ["Reminder visibility is authority based.", "This guide does not create, update, or send reminders."],
      preview: makePreview("CWD reminder", ["Window", "Owner", "Status"]),
    }),
    entry({
      id: "club-website-content-support",
      title: "Club website content support",
      purpose: "Website content support covers coordination for public pages, event copy, images, and club information shown on the website.",
      whoUses: ["CWD / Website Director", "BOD contributors", "President", "Admin"],
      canDo: ["Understand where public content appears", "Coordinate event or project information", "Support corrections through the approved website workflow"],
      steps: ["Identify the public page or module that needs support.", "Collect approved copy, images, and dates.", "Coordinate changes through the club website process.", "Verify the public page after deployment or update."],
      notes: ["This guide does not edit public website content.", "Sensitive member/admin records should never be copied into public content."],
      preview: makePreview("Content support", ["Public page", "Approved copy", "Review state"]),
    }),
  ]),
});
