export const termsSections = [
  {
    id: "about",
    title: "1. About these terms",
    paragraphs: [
      "These terms apply to individuals creating or using an account with the Rotaract Club of Pune Heritage (\u201cRCPH\u201d), whether through the existing-member path or the prospective-member path.",
      "Creating an account does not automatically create, confirm, renew, or guarantee club membership, induction, a Board position, voting rights, event participation, or any particular role.",
      "RCPH operates subject to its applicable club bylaws, the Standard Rotaract Club Constitution, relevant Rotary International and District policies, and decisions validly taken by the club\u2019s Board or General Body.",
    ],
  },
  {
    id: "account-security",
    title: "2. Accurate information and account security",
    paragraphs: ["Users must provide accurate, complete, and current information.", "Users must not:"],
    list: [
      "impersonate another person",
      "create an account using false or misleading information",
      "intentionally conceal information materially relevant to club administration",
      "allow another person to use their account",
      "attempt to gain unauthorized access to club systems or records",
    ],
    after: ["Users are responsible for keeping credentials secure and reporting suspected unauthorized access."],
  },
  {
    id: "eligibility",
    title: "3. Eligibility",
    paragraphs: [
      "Membership with RCPH is intended for eligible students and young professionals who satisfy the club\u2019s applicable membership requirements.",
      "Under the currently adopted RCPH bylaws, members should be under 35 years of age.",
      "Eligibility requirements may be reviewed or updated through valid club procedures. Creating an account does not constitute confirmation that every eligibility requirement has been satisfied.",
    ],
  },
  {
    id: "prospect-accounts",
    title: "4. Prospect accounts and membership approval",
    paragraphs: [
      "A prospect account enables RCPH to administer a person\u2019s participation and potential membership journey. It does not mean that the person has already been admitted or inducted.",
      "Prospective members may be required to:",
    ],
    list: [
      "attend applicable meetings or club activities",
      "participate respectfully and constructively",
      "demonstrate suitable involvement and conduct",
      "provide information reasonably required for membership administration",
      "satisfy the applicable induction criteria",
      "receive Board approval before induction",
    ],
    after: ["The current club bylaws refer to induction after two consecutive meetings or an approved combination of meetings and a club event, subject to the Board\u2019s assessment of conduct, participation, interaction, and involvement."],
  },
  {
    id: "member-accounts",
    title: "5. Existing-member accounts",
    paragraphs: [
      "The existing-member path is intended only for people already recognized in RCPH\u2019s official membership records.",
      "RCPH may verify the account against club records and may reject, restrict, suspend, correct, or reclassify an account where the selected status or requested role does not match official records.",
    ],
  },
  {
    id: "conduct",
    title: "6. Conduct and club values",
    paragraphs: ["Users agree to act honestly, fairly, respectfully, responsibly, and consistently with the values of Rotary and RCPH.", "Prohibited conduct includes:"],
    list: [
      "harassment",
      "discrimination",
      "intimidation",
      "bullying",
      "abusive or threatening conduct",
      "deliberate disruption",
      "misuse of club data, systems, assets, funds, branding, or communication channels",
      "unauthorized representation of RCPH or Rotary",
      "improper use of membership for personal, professional, commercial, or financial advantage",
      "conduct that harms the safety, reputation, functioning, or legitimate interests of RCPH, Rotary, members, partners, participants, or the public",
    ],
  },
  {
    id: "locations",
    title: "7. Meetings and event locations",
    paragraphs: ["RCPH meetings and activities are held primarily in:"],
    list: ["Kothrud, Pune", "Karvenagar, Pune", "Sahakarnagar, Pune"],
    after: [
      "The exact venue may differ depending on event requirements, venue availability, expected attendance, collaboration arrangements, project requirements, safety considerations, or decisions of the organizing team.",
      "Some meetings or events may take place elsewhere in Pune, outside Pune, online, or at a venue arranged by a partner organization.",
      "Users are responsible for checking the final venue, date, reporting time, and instructions before travelling.",
    ],
  },
  {
    id: "expenses",
    title: "8. Travel and personal expenses",
    paragraphs: [
      "Personal commuting, travel, fuel, parking, tolls, accommodation, meals, and similar expenses incurred while attending meetings, events, projects, or activities are the participant\u2019s responsibility and will not be reimbursed.",
      "A separately approved club purchase or officially sanctioned event expense may be reimbursed only where:",
    ],
    list: [
      "it was approved in advance by an authorized club officer",
      "it falls within the applicable approved budget",
      "appropriate bills, receipts, vouchers, or supporting information are provided",
      "reimbursement is permitted under the applicable club financial procedures",
    ],
    after: ["Attendance or participation alone must not be interpreted as approval for reimbursement."],
  },
  {
    id: "attendance",
    title: "9. Attendance and participation",
    paragraphs: ["Members and prospects are expected to meet the participation and attendance requirements applicable to their status.", "The club\u2019s current bylaws include:"],
    list: [
      "regular General Body Meetings",
      "a minimum attendance expectation for members",
      "participation requirements for induction",
      "review of prolonged inactivity or repeated absence",
    ],
    after: ["Meeting frequency, attendance criteria, induction requirements, and participation expectations may be revised through valid club procedures."],
  },
  {
    id: "payments",
    title: "10. Dues, fees, and payments",
    paragraphs: ["Creating an account does not itself create a payment obligation unless an obligation is separately and clearly communicated.", "Members or participants may be required to pay:"],
    list: [
      "annual membership dues",
      "applicable District or Rotary-related dues",
      "event registration charges",
      "project contributions",
      "other amounts properly approved and communicated by RCPH",
    ],
    after: [
      "Amounts, allocations, deadlines, and payment methods may change by Rotary year.",
      "Payments must be made only through authorized channels.",
      "Club dues are generally non-refundable following voluntary resignation or termination, subject to applicable club decisions and procedures.",
    ],
  },
  {
    id: "safety",
    title: "11. Events, safety, and personal responsibility",
    paragraphs: ["Participation may involve ordinary risks associated with meetings, travel, service projects, sports, fellowships, outdoor activities, third-party venues, or collaborative events.", "Participants must:"],
    list: [
      "follow reasonable safety and venue instructions",
      "behave responsibly",
      "comply with applicable law and venue requirements",
      "disclose relevant accessibility or support requirements where appropriate",
      "avoid placing themselves or others at unnecessary risk",
    ],
    after: ["RCPH may cancel, postpone, relocate, limit, or modify an activity where reasonably necessary."],
  },
  {
    id: "restrictions",
    title: "12. Account restrictions and disciplinary action",
    paragraphs: ["RCPH may restrict, suspend, deactivate, or remove an account where reasonably necessary, including where:"],
    list: [
      "information is false or cannot be verified",
      "the incorrect account path was selected",
      "these terms are breached",
      "membership or prospect status ends",
      "a security or privacy risk arises",
      "the account remains inactive",
      "action is taken under the club bylaws or a valid club decision",
    ],
    after: ["Account suspension is not automatically the same as termination of membership. Membership-related actions remain subject to applicable club procedures."],
  },
  {
    id: "essential-communications",
    title: "13. Essential communications",
    paragraphs: ["RCPH may send communications necessary to operate the account or administer club participation, including:"],
    list: [
      "account verification",
      "security notices",
      "prospect or membership status updates",
      "dues administration",
      "attendance administration",
      "registered-event changes",
      "policy changes",
      "terms updates",
      "messages needed to provide the requested account services",
    ],
    after: ["These essential communications are separate from optional event and announcement communications."],
  },
  {
    id: "updates",
    title: "14. Updates to these terms",
    paragraphs: ["RCPH may update these terms to reflect changes in:"],
    list: ["club bylaws", "Rotary or District policies", "law", "club operations", "platform functionality", "data practices"],
    after: ["Material updates should use a new version and effective date. Users may be asked to accept updated terms where appropriate."],
  },
  { id: "contact", title: "15. Contact", paragraphs: ["Rotaract Club of Pune Heritage"], contact: true },
];

export const privacySections = [
  {
    id: "scope",
    title: "1. Scope",
    paragraphs: ["This notice explains how RCPH collects, uses, stores, and manages personal data associated with prospect accounts, member accounts, club participation, and platform administration."],
  },
  {
    id: "data-collected",
    title: "2. Data collected",
    paragraphs: ["Depending on the account path and activities, RCPH may collect:"],
    list: [
      "full name", "email address", "phone number", "authentication identifiers", "account status", "requested and approved role", "prospect or membership status", "signup or application information", "Rotaract history", "motivation and referral information", "hobbies and voluntarily provided profile details", "attendance and participation records", "event registrations", "dues or payment-status records", "role and access permissions", "communications with RCPH", "administrative notes relevant to membership", "technical and security records", "consent records", "other information voluntarily submitted to RCPH",
    ],
  },
  {
    id: "purposes",
    title: "3. Purposes",
    paragraphs: ["RCPH may process data to:"],
    list: [
      "create and secure accounts", "verify identity and membership status", "administer prospect progression and induction", "maintain club records", "manage attendance", "manage dues and payment status", "manage event participation", "provide role-based access", "organize club activities", "send essential operational messages", "administer governance and permissions where applicable", "protect the platform", "prevent misuse", "respond to corrections, account requests, and grievances", "comply with applicable club, District, Rotary, financial, and legal obligations",
    ],
  },
  {
    id: "processing",
    title: "4. Mandatory and optional processing",
    paragraphs: ["Data necessary to create and administer the account is processed on the basis of the mandatory acceptance provided during signup.", "Optional event and announcement communications are based on a separate, voluntary choice.", "Declining optional communications must not prevent:"],
    list: ["account creation", "prospect participation", "membership verification", "induction", "access to normal account functionality"],
  },
  {
    id: "sharing",
    title: "5. Authorized access and sharing",
    paragraphs: ["Data may be accessed by authorized people who reasonably need it for:"],
    list: ["account administration", "membership administration", "prospect management", "attendance", "dues", "event management", "club communications", "governance", "technical support", "security"],
    after: ["RCPH may use service providers for:"],
    secondList: ["authentication", "hosting", "database storage", "email delivery", "technical infrastructure", "security"],
    final: ["RCPH does not sell personal data.", "Account creation does not make submitted data public."],
  },
  {
    id: "retention",
    title: "6. Data retention",
    paragraphs: ["Data may be retained for as long as reasonably necessary to:"],
    list: ["operate the account", "administer membership", "maintain club, attendance, financial, event, or governance records", "resolve disputes", "meet audit, security, legal, District, Rotary, or club obligations", "preserve legitimate organizational history"],
    after: ["Deletion or account closure may not remove records that must reasonably be retained for lawful, financial, governance, security, or historical purposes."],
  },
  {
    id: "choices",
    title: "7. User choices and requests",
    paragraphs: ["Users may request:"],
    list: ["correction", "updating", "review of account data", "withdrawal of optional communications consent", "account closure", "deletion where applicable", "grievance review"],
    after: ["Requests, including withdrawal of optional communications consent, can currently be sent to the verified club email below."],
  },
  {
    id: "security",
    title: "8. Security",
    paragraphs: ["RCPH uses reasonable technical and organizational safeguards but cannot promise absolute security.", "Users are responsible for protecting their login credentials."],
  },
  {
    id: "changes",
    title: "9. Changes",
    paragraphs: ["Privacy-notice updates must use a version and effective date.", "Material changes may require a new notice or renewed acceptance."],
  },
  { id: "contact", title: "10. Contact", paragraphs: ["Rotaract Club of Pune Heritage"], contact: true },
];
