import { useState } from "react";
import { useLocation } from "react-router-dom";
import AdminShell from "../../features/admin/AdminShell";
import { BodOperationsModule, ClubAttendanceModule, DistrictModule } from "../../features/admin/modules/AttendanceModules";
import { AccountsModule, CommandCenter, MembersModule, ReportsModule } from "../../features/admin/modules/CoreModules";
import DzrVisitModule from "../../features/admin/modules/DzrVisitModule";
import { AnnouncementsModule, ProspectsModule } from "../../features/admin/modules/EngagementModules";
import { FinesModule, TreasuryModule } from "../../features/admin/modules/FinanceModules";
import LocksModule from "../../features/admin/modules/LocksModule";
import ResolutionsModule from "../../features/admin/resolutions/ResolutionsModule";
import { AdminError, AdminLoading, AdminNotice } from "../../features/admin/shared/AdminStates";
import { clearAdminCaches } from "../../features/admin/shared/adminService";
import useAdminData from "../../features/admin/shared/useAdminData";
import VisitSubmissionsModule from "../../features/admin/visit/VisitSubmissionsModule";
import { clearBodEventCache } from "../../features/bod-tools/bodEventService";
import { clearDashboardDataCache } from "../../features/dashboard/dashboardService";
import useAuth from "../../hooks/useAuth";
import { formatRotaractorName } from "../../utils/memberName";
import "../../styles/components/admin.css";

export default function AdminPage() {
  const { access, user, signOut } = useAuth(); const location = useLocation(); const [notice, setNotice] = useState(null); const uid = user?.uid || ""; const segment = location.pathname.replace(/^\/admin\/?/, ""); const { data, locks, moduleState } = useAdminData({ uid, enabled: Boolean(uid && access?.canAccessAdminTools) });
  const requirements = { "": ["members", "events", "attendance", "fines", "treasury", "users"], requests: ["users"], members: ["members", "users", "events", "attendance", "fines"], attendance: ["members", "events", "attendance"], bod: ["bodMembers", "bodMeetings", "bodAttendance"], district: ["members", "districtEvents", "districtAttendance"], fines: ["members", "fines"], treasury: ["members", "treasury"], reports: ["events"], "dzr-visit": ["members", "events", "attendance", "bodMembers", "bodMeetings", "bodAttendance", "fines", "treasury"] };
  const canAccessLockTools = access?.canAccessLockTools === true || access?.canAccessPresidentControls === true;
  const canAccessResolutionTools = access?.canAccessResolutionTools === true;
  const routeDenied = (segment === "locks" && !canAccessLockTools) || (segment === "resolutions" && !canAccessResolutionTools);
  const state = moduleState(...(requirements[segment] || []));
  async function handleSignOut() { clearAdminCaches(uid); clearBodEventCache(uid); clearDashboardDataCache(uid); await signOut(); }
  let content;
  if (routeDenied) content = <AdminError message="You do not have access to this protected Admin module." />;
  else if (state.status === "loading") content = <AdminLoading />;
  else if (state.status === "error") content = <AdminError message={state.error} />;
  else if (segment === "") content = <CommandCenter data={data} access={access} uid={uid} onNotice={setNotice} />;
  else if (segment === "requests") content = <AccountsModule users={data.users} access={access} uid={uid} onNotice={setNotice} />;
  else if (segment === "members") content = <MembersModule members={data.members} users={data.users} events={data.events} attendance={data.attendance} fines={data.fines} uid={uid} onNotice={setNotice} />;
  else if (segment === "attendance") content = <ClubAttendanceModule data={data} lock={locks.attendance} uid={uid} onNotice={setNotice} />;
  else if (segment === "bod") content = <BodOperationsModule data={data} lock={locks.bodAttendance} uid={uid} onNotice={setNotice} />;
  else if (segment === "district") content = <DistrictModule data={data} lock={locks.attendance} uid={uid} onNotice={setNotice} />;
  else if (segment === "prospects") content = <ProspectsModule uid={uid} onNotice={setNotice} />;
  else if (segment === "announcements") content = <AnnouncementsModule uid={uid} onNotice={setNotice} />;
  else if (segment === "resolutions") content = <ResolutionsModule uid={uid} onNotice={setNotice} />;
  else if (segment === "fines") content = <FinesModule fines={data.fines} members={data.members} lock={locks.fines} uid={uid} onNotice={setNotice} />;
  else if (segment === "treasury") content = <TreasuryModule transactions={data.treasury} members={data.members} lock={locks.treasury} uid={uid} onNotice={setNotice} />;
  else if (segment === "locks") content = <LocksModule locks={locks} access={access} uid={uid} onNotice={setNotice} />;
  else if (segment === "reports") content = <ReportsModule events={data.events} />;
  else if (segment === "visit-submissions") content = <VisitSubmissionsModule onNotice={setNotice} />;
  else if (segment === "dzr-visit") content = <DzrVisitModule data={data} />;
  else content = <AdminError message="This Admin module does not exist." />;
  return <main className="admin-page"><AdminShell access={access} displayName={formatRotaractorName(access?.user?.name || user?.displayName || "RCPH Admin", access?.user || access?.storedRole)} onSignOut={handleSignOut}><AdminNotice notice={notice} onDismiss={() => setNotice(null)} />{content}</AdminShell></main>;
}
