// Safe client mirror of functions/lib/positions.js and the legacy admin catalog.
// Canonical keys are submitted unchanged; server validation remains authoritative.
export const POSITION_GROUPS = Object.freeze([
  Object.freeze({ key: "admin", label: "Admin Positions" }),
  Object.freeze({ key: "bod", label: "BOD Positions" }),
  Object.freeze({ key: "co-admin", label: "Co-Admin Positions" }),
  Object.freeze({ key: "co-bod", label: "Co-BOD Positions" }),
]);

export const POSITION_CATALOG = Object.freeze([
  ["president", "President", "PRES", "admin", 1, "president", true, ["Club President"]],
  ["immediate-past-president", "Immediate Past President", "IPP", "admin", 2, "admin", true, ["IPP"]],
  ["vice-president", "Vice President", "VP", "admin", 3, "admin", true, ["Vice-President", "VP"]],
  ["secretary", "Secretary", "SEC", "admin", 4, "admin", true, ["Club Secretary"]],
  ["joint-secretary", "Joint Secretary", "JSEC", "admin", 5, "admin", true, ["Joint-Secretary"]],
  ["treasurer", "Treasurer", "TREAS", "admin", 6, "admin", true, ["Club Treasurer"]],
  ["club-advisor", "Club Advisor", "ADV", "admin", 7, "admin", true, ["Advisor"]],
  ["csd", "Club Service Director", "CSD", "bod", 20, "bod", true, ["Club Service"]],
  ["cmd", "Community Service Director", "CMD", "bod", 21, "bod", true, ["Community Service"]],
  ["isd", "International Service Director", "ISD", "bod", 22, "bod", true, ["International Service"]],
  ["pdd", "Professional Development Director", "PDD", "bod", 23, "bod", true, ["Professional Development"]],
  ["rrro", "Rotary Rotaract Relations Officer", "RRRO", "bod", 24, "bod", true, ["Rotary-Rotaract Relations Officer"]],
  ["pro", "Public Relations Officer", "PRO", "bod", 25, "bod", true, ["Public Relations"]],
  ["dei", "DEI Director", "DEI", "bod", 26, "bod", true, ["Diversity Equity Inclusion Officer", "Diversity Equity and Inclusion Officer"]],
  ["editor", "Editor", "EDITOR", "bod", 27, "bod", true, ["Club Editor"]],
  ["cwd", "Website Director", "CWD", "bod", 28, "bod", true, ["Club Website Director", "Web Director"]],
  ["sports-representative", "Sports Representative", "SPORTS", "bod", 29, "bod", true, ["Club Sports Representative", "Sports Director"]],
  ["wrwc", "World Rotaract Week Chairperson", "WRWC", "bod", 30, "bod", true, ["World Rotaract Week Chair"]],
  ["wr", "Women's Representative", "WR", "bod", 31, "bod", true, ["Womens Representative", "Women Representative"]],
  ["saa", "Sergeant-at-Arms", "SAA", "bod", 32, "bod", true, ["Sergeant at Arms"]],
  ["co-president", "Co-President", "CPRES", "co-admin", 50, "admin", true, ["Co President"]],
  ["co-vice-president", "Co-Vice President", "CVP", "co-admin", 51, "admin", true, ["Co Vice President", "Co-Vice-President"]],
  ["co-secretary", "Co-Secretary", "CSEC", "co-admin", 52, "admin", true, ["Co Secretary", "Co Club Secretary"]],
  ["co-treasurer", "Co-Treasurer", "CTREAS", "co-admin", 53, "admin", true, ["Co Treasurer", "Co Club Treasurer"]],
  ["co-club-advisor", "Co-Club Advisor", "CADV", "co-admin", 54, "admin", true, ["Co Club Advisor", "Co Advisor"]],
  ["co-csd", "Co-Club Service Director", "CCSD", "co-bod", 70, "bod", true, ["Co Club Service", "Co-CSD"]],
  ["co-cmd", "Co-Community Service Director", "CCMD", "co-bod", 71, "bod", true, ["Co Community Service", "Co-CMD"]],
  ["co-isd", "Co-International Service Director", "CISD", "co-bod", 72, "bod", true, ["Co International Service", "Co-ISD"]],
  ["co-pdd", "Co-Professional Development Director", "CPDD", "co-bod", 73, "bod", true, ["Co Professional Development", "Co-PDD"]],
  ["co-rrro", "Co-Rotary Rotaract Relations Officer", "CRRRO", "co-bod", 74, "bod", true, ["Co Rotary-Rotaract Relations Officer", "Co-RRRO"]],
  ["co-pro", "Co-Public Relations Officer", "CPRO", "co-bod", 75, "bod", true, ["Co Public Relations", "Co-PRO"]],
  ["co-dei", "Co-DEI Director", "CDEI", "co-bod", 76, "bod", true, ["Co Diversity Equity Inclusion Officer", "Co Diversity Equity and Inclusion Officer"]],
  ["co-editor", "Co-Editor", "CEDITOR", "co-bod", 77, "bod", true, ["Co Club Editor"]],
  ["co-cwd", "Co-Website Director", "CCWD", "co-bod", 78, "bod", true, ["Co Club Website Director", "Co Web Director"]],
  ["co-sports-representative", "Co-Sports Representative", "CSPORTS", "co-bod", 79, "bod", true, ["Co Club Sports Representative", "Co Sports Director"]],
  ["co-wrwc", "Co-World Rotaract Week Chairperson", "CWRWC", "co-bod", 80, "bod", true, ["Co World Rotaract Week Chair"]],
  ["co-wr", "Co-Women's Representative", "CWR", "co-bod", 81, "bod", true, ["Co Womens Representative", "Co Women Representative"]],
  ["co-saa", "Co-Sergeant-at-Arms", "CSAA", "co-bod", 82, "bod", true, ["Co Sergeant at Arms"]],
].map(([key, displayTitle, avenueCode, group, sortOrder, effectiveRole, bodRoster, aliases]) => Object.freeze({
  key,
  displayTitle,
  avenueCode,
  group,
  sortOrder,
  effectiveRole,
  bodRoster,
  resolutionVoter: bodRoster === true,
  aliases: Object.freeze([displayTitle, avenueCode, ...aliases]),
  active: true,
})));

export const WEBSITE_DIRECTOR_POSITION_KEY = "cwd";
